// src/App.jsx
import { useState, useCallback } from 'react';
import UploadCSV from './components/UploadCSV';
import FilterPanel from './components/FilterPanel';
import ContestView from './components/ContestView';
import { filterQuestions, generateContest } from './utils/filterQuestions';

function App() {
  const [questions, setQuestions] = useState([]);
  const [filters, setFilters] = useState({
    types: [],
    topics: [],
    sources: [],
  });
  const [activeFilters, setActiveFilters] = useState({
    types: [],
    topics: [],
    sources: [],
    includeCompleted: false,
  });

  const handleUpload = useCallback(({ questions: newQuestions, filters: newFilters }) => {
    setQuestions(newQuestions);
    setFilters(newFilters);
  }, []);

  const handleFilterChange = useCallback((newFilters) => {
    setActiveFilters(newFilters);
  }, []);

  const filteredQuestions = filterQuestions(questions, activeFilters);

  const handleGenerateContest = useCallback((questions, difficultyCombination) => {
    return generateContest(questions, difficultyCombination);
  }, []);

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-gray-900">
            DSA Contest Generator
          </h1>
        </div>
      </header>

      <main className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0">
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            {/* Left Sidebar */}
            <div className="lg:col-span-1 space-y-6">
              <UploadCSV onUpload={handleUpload} />
              {questions.length > 0 && (
                <FilterPanel
                  filters={filters}
                  onFilterChange={handleFilterChange}
                />
              )}
            </div>

            {/* Main Content */}
            <div className="lg:col-span-3">
              <ContestView
                questions={filteredQuestions}
                onGenerateContest={handleGenerateContest}
              />
            </div>
          </div>
      </div>
      </main>
      </div>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import FileUpload from '@/components/FileUpload.vue'
import FilterPanel from '@/components/FilterPanel.vue'
import QuestionList from '@/components/QuestionList.vue'
import { useQuestionStore } from '@/store/useQuestionStore'

const store = useQuestionStore()
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <header class="bg-white shadow-sm">
      <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold text-gray-900">
          DSA Contest Generator
        </h1>
      </div>
    </header>

    <main class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <div class="px-4 py-6 sm:px-0">
        <div class="grid grid-cols-1 lg:grid-cols-4 gap-6">
          <!-- Left Sidebar -->
          <div class="lg:col-span-1 space-y-6">
            <FileUpload />
            <FilterPanel v-if="store.questions.length" />
          </div>

          <!-- Main Content -->
          <div class="lg:col-span-3">
            <QuestionList />
          </div>
        </div>
      </div>
    </main>
  </div>
</template>
